### ISSUE TITLE
Bug: Roguelike `FontInfo` misbehaving with IndigoSandbox

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/roguelike-starterkit#44]
There's something up with doing the following:

`val fonts: Set[FontInfo]  = Set(RoguelikeTiles10x10.Fonts.fontInfo)`

It fails to link correctly, there's a lot of compiler output (from Mill, haven't tried sbt, shouldn't matter...?) about `Option`s (output below).

Pretty sure I did this recently in an `IndigoGame` (Rogue-paint?) and it was fine.

Have tried with Scala.js `1.13.2` and `1.14.0`, and RLSK `0.3.2` and `0.4.0` - same thing happens.

I wondered if it was something about early evaluation perhaps? (https://github.com/PurpleKingdomGames/indigo/issues/647)

```
at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2730)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:2139)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.newReceiver$1(FunctionEmitter.scala:2240)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.genNormalApply$1(FunctionEmitter.scala:2247)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2294)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2730)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:2139)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.newReceiver$1(FunctionEmitter.scala:2240)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.genNormalApply$1(FunctionEmitter.scala:2247)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2294)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2143)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$transformStat$1(FunctionEmitter.scala:611)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$unnest$8(FunctionEmitter.scala:1160)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.unnest(FunctionEmitter.scala:1140)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.unnest(FunctionEmitter.scala:1158)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:607)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:2023)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.redo$1(FunctionEmitter.scala:1506)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1574)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:898)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunctionInternal(FunctionEmitter.scala:519)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$desugarToFunction$1(FunctionEmitter.scala:499)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.performOptimisticThenPessimisticRuns(FunctionEmitter.scala:410)
        at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunction(FunctionEmitter.scala:499)
        at org.scalajs.linker.backend.emitter.FunctionEmitter.desugarToFunction(FunctionEmitter.scala:285)
        at org.scalajs.linker.backend.emitter.FunctionEmitter.desugarToFunction(FunctionEmitter.scala:263)
        at org.scalajs.linker.backend.emitter.ClassEmitter.$anonfun$genJSConstructorFun$3(ClassEmitter.scala:338)
        at scala.Option.fold(Option.scala:263)
        at org.scalajs.linker.backend.emitter.ClassEmitter.genJSConstructorFun(ClassEmitter.scala:330)
        at org.scalajs.linker.backend.emitter.ClassEmitter.genScalaClassConstructor(ClassEmitter.scala:182)
        at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$9(Emitter.scala:493)
        at org.scalajs.linker.backend.emitter.Emitter$MethodCache.getOrElseUpdate(Emitter.scala:884)
        at org.scalajs.linker.backend.emitter.Emitter.genClass(Emitter.scala:493)
        at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$4(Emitter.scala:184)
        at scala.collection.immutable.List.map(List.scala:250)
        at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$2(Emitter.scala:184)
        at scala.collection.immutable.List.map(List.scala:246)
        at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$1(Emitter.scala:181)
        at org.scalajs.logging.Logger.time(Logger.scala:42)
        at org.scalajs.logging.Logger.time$(Logger.scala:40)
        at org.scalajs.logging.ScalaConsoleLogger.time(ScalaConsoleLogger.scala:15)
        at org.scalajs.linker.backend.emitter.Emitter.emitOnce(Emitter.scala:185)
        at org.scalajs.linker.backend.emitter.Emitter.emitAvoidGlobalClash(Emitter.scala:154)
        at org.scalajs.linker.backend.emitter.Emitter.emitInternal(Emitter.scala:129)
        at org.scalajs.linker.backend.emitter.Emitter.emit(Emitter.scala:81)
        at org.scalajs.linker.backend.BasicLinkerBackend.$anonfun$emit$1(BasicLinkerBackend.scala:65)
        at org.scalajs.logging.Logger.time(Logger.scala:42)
        at org.scalajs.logging.Logger.time$(Logger.scala:40)
        at org.scalajs.logging.ScalaConsoleLogger.time(ScalaConsoleLogger.scala:15)
        at org.scalajs.linker.backend.BasicLinkerBackend.emit(BasicLinkerBackend.scala:65)
        at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by davesmith00000** [comment]
Duplicate of #49
